language: go

go:
  - 1.6

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - cd $GOPATH/src/github.com/flowpl/log && goveralls -service=travis-ci -covermode=count -repotoken $COVERALLS_REPO_TOKEN
