language: go

go:
  - 1.6

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count github.com/flowpl/log -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_REPO_TOKEN

after_script:
  - $GOPATH/bin/goveralls
